### PR TITLE
Add syntax highlight to examples in README

### PR DESCRIPTION
**Pull request by nicoddemus**

### CODE REVIEW

**Comment by nicoddemus** [comment]
Oh I've created this PR in main repository, sorry about that. Didn't realize I had write access to it.

Let me know if you would like me to close this PR and re-open from a fork instead.

**Comment by pquentin** [comment]
This is currently blocked on https://github.com/python-trio/trio/issues/1402, but we'll merge it as soon as possible. Thanks!

**Comment by pquentin** [comment]
TestHTTPS.test_client_no_intermediate failed with a BrokenPipeError. #200

**Comment by pquentin** [comment]
Thanks!

**Pull request merged**
