### PR TITLE
Add API for exceptions

### PR DESCRIPTION
**Pull request by sethmlarson**
Mostly based off of Requests' exceptions module. I went with `exceptions` instead of `errors`, I'm fine either way though.

### CODE REVIEW

**Comment by pquentin** [comment]
`exceptions` sounds better to me than `errors` 👍

**Comment by njsmith** [comment]
I guess I have a preference for following `requests` on little things like this where we only have a weak preference that's purely about taste? Because migration pain is a real thing we should try to minimize.

OTOH Trio's approach is to just drop the exceptions into the top-level namespace, because duh, obviously `hip.ConnectionError` is an error, you don't need a `.errors.` or `.exceptions.` in there to emphasize the point.

**Comment by pquentin** [comment]
And since that was not stated explicitly so far, requests exceptions live in `request.exceptions`, and they all inherit from `requests.exceptions.RequestException`, the same way everything here ends up inheriting from `HipError`.

So... I think this is ready to merge? I think this list is easy to tweak later, but it's valuable to have it in so that the other PRs can refer to it?

**Comment by sethmlarson** [comment]
@njsmith I can pull all of them into global namespace. Mostly wanted feedback on the errors I picked to define. :)

**Comment by sethmlarson** [comment]
Pulled into the global namespace now. We can expand the exceptions list as well in the future, wondering if any jump out as something we don't need.

I wanted to add a lot of the specific cases that are likely to happen for certificates especially, because they are errors that users are very likely to encounter.

**Comment by sethmlarson** [comment]
Closing these API PRs in favor of a scratch branch.

**Pull request closed without merging**
