### PR TITLE
Rename inject_into_urllib3/extract_from_urllib3

### PR DESCRIPTION
**Pull request by pquentin**

### CODE REVIEW

**Comment by njsmith** [comment]
Does this code even work on hip? It seems like it requires intimate knowledge of the underlying I/O system...

**Comment by pquentin** [comment]
@njsmith Oh, no, this does not work at all and caused us [problems](https://github.com/python-trio/hip/pull/42) in the past. This is also the first reason why we don't support atlernate TLS backends. So the new names still don't work. But I figured it wasn't a reason to keep the old names.

**Comment by sethmlarson** [comment]
If the code doesn't work should we get rid of the inject functions? Or are we planning for them to work?

**Comment by pquentin** [comment]
We need to find a way to make the functionality work without mutating sys.modules. But I don't know how to do that! Should I leave the old name for the time being, or is the rename still valuable even though those functions don't work?

**Comment by njsmith** [comment]
I opened an issue to discuss the substantive questions about these module's future, so it doesn't end up collecting on a minor search/replace PR :-) https://github.com/python-trio/hip/issues/177

I guess for this PR itself.... I think it's quite possible that we'll delete this code entirely, but I take that as an argument for merging the PR. The PR's not making anything worse, it lets us decouple the name update work from the TLS library support work, and we're going to revisit this anyway so let's not get hung up here.

**Pull request merged**
