### PR TITLE
Asyncify TestPoolManager tests

### PR DESCRIPTION
**Pull request by pquentin**
This pull request is based on https://github.com/python-trio/hip/pull/225, and shows that the migration is easy!

### CODE REVIEW

**Comment by pquentin** [comment]
I'd like to understand the coverage drop before merging this.

**Comment by pquentin** [comment]
Unfortunately codecov won't let me see the coverage change (all diffs are empty), but #227 is certainly part of the problem

**Comment by pquentin** [comment]
> I'd like to understand the coverage drop before merging this.

Actually, I'm not sure that I want to understand it. :) I've been meaning to do it for two months, but I lack the motivation. @sethmlarson @njsmith Do you mind if I merge it as is, and look at the coverage issue "later"?

**Comment by sethmlarson** [comment]
@pquentin Let's merge, coverage can always be fixed later. Onwards to victory! :)

**Comment by pquentin** [comment]
Thanks!

**Pull request merged**
