### PR TITLE
Add gh actions for CI on macos

### PR DESCRIPTION
**Pull request by RatanShreshtha**

### CODE REVIEW

**Comment by sethmlarson** [comment]
Codecov having problems, @pquentin didn't you mention something about maybe us needing to use the token?

**Comment by pquentin** [comment]
@sethmlarson Right, we can't use `${{ secrets.CODECOV_TOKEN }}` and should continue to hardcode the codecov token here

**Comment by pquentin** [comment]
Thank you!

So now that this works, we'll need to think about how we're going to organize this. @njsmith convinced me in https://github.com/python-trio/hip/pull/153 that it was valuable to name the jobs after the platform. We now expect `Windows (2.7)`, but the build is now named `test (windows-latest, 2.7) `. I think we should move most of the logic in a `.github/workflows/ci.sh` file so that we can continue to name our build after the platform. What do you think?

**Comment by RatanShreshtha** [comment]
I think we shouldn't name the tests as just platform as in that case the job name will only tell us it doing something on platform `Windows (2.7)` but not what so I am more inclined towards name like `Windows Tests (2.7)`.

What do you think @njsmith and @pquentin ?

**Comment by pquentin** [comment]
I'm not sure if this is useful: when I see "Windows (3.7)" I can guess that we're running our tests with Python 2.7 on Windows. But if you prefer to use "Windows tests" that's fine too.

**Comment by pquentin** [comment]
Thanks. Can you please switch from "windows" to "Windows" so that it matches the status checks that are currently required? And while we're at it, let's use "macOS".

We can worry about refactoring in a shell script later.

**Comment by pquentin** [comment]
Thanks!

**Pull request merged**
