### PR TITLE
Add Gitter chat button to docs

### PR DESCRIPTION
**Pull request by sethmlarson**
Makes it easy for users that have questions / want to discuss Hip to find our Gitter room.
This approach was taken from https://github.com/tiangolo/fastapi/pull/1061

### CODE REVIEW

**Comment by njsmith** [comment]
Whoa, that's slick! Now I want that for the trio docs too...

Nit-picky question: I wonder if it's possible to put an informational banner at the top of the sidecar chat window, to give some hint about what folks are looking at? Like there's a big difference between "here's a project's general chat channel" versus "talk to a sales agent now (but actually they're a robot)!", and I think people will be more comfortable and get better results if we can help them calibrate their expectations a little.

**Comment by njsmith** [comment]
I'm imagining something like "This is the general [project] chat channel, which anyone can join. We're always happy to answer questions, but sometimes we're busy with other things so it might take a bit. Please remember our [code of conduct]. You can also join the channel here: [link]"

**Comment by sethmlarson** [comment]
@njsmith I'll investigate if there's something we can hook into and inject our own text, it'd also be good to be able to change the color of the button to match the theme more closely.

**Comment by njsmith** [comment]
The docs appear to be here: https://sidecar.gitter.im/ (scroll down the pane on the left)

It seems to be pretty customizable: you can make your own arbitrary HTML elements for the button and chat pane, and tell it to use them.

**Pull request closed without merging**
