### PR TITLE
Add ci for ubuntu using gh-action

### PR DESCRIPTION
**Pull request by RatanShreshtha**

### CODE REVIEW

**Comment by pquentin** [comment]
I don't understand :/

**Comment by pquentin** [comment]
@RatanShreshtha I spend hours on this in the context of urllib3, see https://github.com/urllib3/urllib3/pull/2035 for the fix. Maybe the issue is different here since we don't have PySocks support, I'm not sure.

**Comment by RatanShreshtha** [comment]
I am thinking about using https://github.com/nektos/act on my machine to figure out what is happening.

**Comment by pquentin** [comment]
By the way @njsmith agreed to drop Python 2 support: https://github.com/python-hyper/h11/issues/114

If the test_source_address issue is only showing up there, that could help! (I'm seeing it on urllib3 too by the way)

**Comment by RatanShreshtha** [comment]
Then I am going to remove python 2 from the list of python version and update the PR

**Comment by pquentin** [comment]
Yes, let's just update the CI we'll focus on removing the Python 2 code later

**Comment by pquentin** [comment]
You only need to remove 2.7 from .travis.yml and we'll be good 👍

**Comment by RatanShreshtha** [comment]
I think PR has set checks for windows with python 2.7

**Comment by pquentin** [comment]
Thanks!

**Pull request merged**
