### PR TITLE
Tweak .gitignore

### PR DESCRIPTION
**Pull request by pquentin**
I was mostly annoyed by coverage.xml here.

### CODE REVIEW

**Comment by njsmith** [comment]
I guess if you do an in-place install (`python setup.py develop` or `pip install -e .`) then you'll still end up with files in `_sync`? Might be best to keep it in `.gitignore`, to make sure they can't accidentally get checked in.

**Comment by pquentin** [comment]
Actually setuptools development mode does not build the package, so it does not generate the _sync files. (This also means it's not very useful for us.)

**Comment by njsmith** [comment]
Wat, really? That's weird. If you have extension modules, then it definitely does build the package in-place (equivalent of `setup.py build_ext --inplace`), but I guess there must be a special case where it only runs `built_ext`, not `build_py`?

**Comment by njsmith** [comment]
...anyway, I guess it wouldn't hurt to have `/_sync/` in the `.gitignore` just in case, but yeah, that does make it less urgent. Feel free to either add that or not, and then merge :-)

**Comment by pquentin** [comment]
Okay I've added it to the tasks of https://github.com/python-trio/hip/pull/181 so that I don't have to add back src/urllib3/_sync/ and then change it to src/hip/_sync/ a few days later. Thanks for the review, merging!

**Pull request merged**
