### PR TITLE
Add API for decoding Response bodies

### PR DESCRIPTION
**Pull request by sethmlarson**
The number of times this single bit of functionality has been re-implemented. :)

### CODE REVIEW

**Comment by njsmith** [comment]
I think I'm missing something :-). Over in the main branch we already have a much more sophisticated version of this that we inherited from urllib3, right? and this is an internal implementation detail, not part of the API, right? So what's it doing here?

**Comment by sethmlarson** [comment]
That's true, don't need the implementation just the `BaseDecoder` for the `BaseResponse.decoder` API.

**Comment by njsmith** [comment]
Obviously we'll need something like this internally, but for the public API, do you think we can restrict it to just `automatic_decompression=True/False` and hide all the rest as implementation details?

**Comment by pquentin** [comment]
In case it somehow affects the public API, here's an interesting comment from Cory in Response.read:

https://github.com/python-trio/hip/blob/056c3095631de149840b7719f2023b74362f6a1f/src/urllib3/_async/response.py#L394-L403

(I don't think it should affect the API, but it seems interesting to know about that.)

**Comment by njsmith** [comment]
We can limit how much we overread by, at least for zlib – see the `max_length` argument to `Decompress.decompress`: https://docs.python.org/3/library/zlib.html#zlib.Decompress.decompress

**Comment by sethmlarson** [comment]
We'll keep this an internal API then, for now closing this.

**Pull request closed without merging**
